### PR TITLE
Update CONTRIBUTING.md

### LINKED ISSUE #7: CONTRIBUTING.mdのタイプミス
# Problem subject

- [ ] Contracts
- [ ] Tests
- [x] Other

[ If other, please write here problem subject ]

# Description

https://github.com/dev-protocol/repository-token/blob/master/.github/CONTRIBUTING.md

The colon is a semicolon.
```
3. Changes something; run npm run lint
```

# Expected behavior/contents

[ Please write here the expected behavior/contents ]

# Actual behavior/contents

[ Please write here the actual behavior/contents ]

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this issue
- [ ] I don't enter to Dev Challenge with this issue

If you enter, please edit the following sections.

## Address

0x27ef834D4A530C8ba24006c88e67524A5d30eD27

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

### PR DESCRIPTION
**Pull request by narita1980**
# Description

[ Please write here what changes this pull request ]

# Why

[ Please write here about why needs this change ]

# Code

- [x] I ran `npm run lint`

# Dev Challenge

Entry to [Dev Challenge](https://github.com/dev-protocol/repository-token/blob/master/docs/DEV_CHALLENGE.md).

- [x] I entry to Dev Challenge with this pull request
- [ ] I don't enter to Dev Challenge with this pull request

If you enter, please edit the following sections.

## Address

0x27ef834D4A530C8ba24006c88e67524A5d30eD27

## Severity

During the Dev Challenge, you can receive Dev tokens depending on the severity of this pull request. Please select one of your expectations.

- [ ] Critical
- [ ] High
- [ ] Medium
- [ ] Low
- [x] Note

_Severity and example are:_

| Severity | Points | e.g.                                                                                              |
| -------- | ------ | ------------------------------------------------------------------------------------------------- |
| Critical | 100    | Update token model, Update the core of this software.                                             |
| High     | 50     | Fix vulnerability, Make the Developer Rewards Program better, etc.; Fix or Kaizen unknown issues. |
| Medium   | 20     | Add implementation, Fix test, Refactoring, etc.; Fix to follow whitepaper.                        |
| Low      | 4      | Empty test, Rename variable, etc.; Fix without implementation.                                    |
| Note     | 1      | Typo, Sentence mistakes, etc.; Fix not related to software.                                       |

When you fix an issue reported by others, severity points are divided by the following ratio:

| Reporter | Resolver |
| -------- | -------- |
| 20%      | 80%      |

# Related Issues

Fixes #7  .

---

# Code of Conduct

By submitting this pull request, I confirm I've read and complied with the [CoC](https://github.com/dev-protocol/repository-token/blob/master/CODE_OF_CONDUCT.md) 🖖

### CODE REVIEW

**Comment by aggre** [comment]
Thank you for your contribute!

Only this part is written as a series of sentences. So, it's difficult to understand.

What do you think of changing to "`After changes something:`" as a better idea?

---

I don't have an objection to your Severity point.

**Comment by narita1980** [comment]
> Thank you for your contribute!
> 
> Only this part is written as a series of sentences. So, it's difficult to understand.
> 
> What do you think of changing to "`After changes something:`" as a better idea?
> 
> I don't have an objection to your Severity point.

確かにそっちの方がよいですね！
それで修正しますー

**Comment by narita1980** [comment]
@aggre 
> Thank you for your contribute!
> 
> Only this part is written as a series of sentences. So, it's difficult to understand.
> 
> What do you think of changing to "`After changes something:`" as a better idea?
> 
> I don't have an objection to your Severity point.

修正しました！
※あと、
```
git clone git@github.com:YOUR/repository-token.git cd repository-token
```
となっていたので
```
git clone git@github.com:YOUR/repository-token.git
cd repository-token
```
と変更してます

**Comment by aggre** [comment]
ありがとうございます！

**Pull request merged**
